import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export const generateIncidentPDF = async (incident, accident) => {
  const doc = new jsPDF();
  const pageHeight = doc.internal.pageSize.getHeight();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;
  let yPosition = margin;

  // Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.text('🚦 INCIDENT REPORT', pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 15;

  // Divider
  doc.setDrawColor(0, 0, 0);
  doc.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 10;

  // Report Details
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);

  const reportData = [
    { label: 'Report ID:', value: incident.id || 'N/A' },
    { label: 'Timestamp:', value: new Date(incident.timestamp).toLocaleString() },
    { label: 'Location:', value: incident.location || 'Unknown' },
    { label: 'Latitude:', value: incident.latitude?.toFixed(6) || 'N/A' },
    { label: 'Longitude:', value: incident.longitude?.toFixed(6) || 'N/A' },
  ];

  reportData.forEach((item) => {
    doc.setFont('helvetica', 'bold');
    doc.text(`${item.label}`, margin, yPosition);
    doc.setFont('helvetica', 'normal');
    doc.text(`${item.value}`, margin + 50, yPosition);
    yPosition += 8;
  });

  yPosition += 10;

  // Severity Section
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.text('SEVERITY INFORMATION', margin, yPosition);
  yPosition += 10;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);

  const severity = incident.severity || 'MEDIUM';
  const severityColor = severity === 'HIGH' ? [255, 0, 0] : severity === 'MEDIUM' ? [255, 165, 0] : [0, 128, 0];

  doc.setFillColor(severityColor[0], severityColor[1], severityColor[2]);
  doc.rect(margin, yPosition - 2, 15, 8, 'F');
  doc.setFont('helvetica', 'bold');
  doc.text(`Severity Level: ${severity}`, margin + 20, yPosition + 2);

  yPosition += 12;

  const severityData = [
    { label: 'Vehicles Involved:', value: incident.vehicles_involved || 0 },
    { label: 'Pedestrians Detected:', value: incident.pedestrians_detected || 0 },
    { label: 'Speed (km/h):', value: incident.speed || 'N/A' },
    { label: 'Injury Risk Score:', value: `${(incident.injury_risk_score || 0).toFixed(2)}/10` },
  ];

  severityData.forEach((item) => {
    doc.setFont('helvetica', 'bold');
    doc.text(`${item.label}`, margin, yPosition);
    doc.setFont('helvetica', 'normal');
    doc.text(`${item.value}`, margin + 50, yPosition);
    yPosition += 8;
  });

  yPosition += 10;

  // Emergency Response Section
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.text('EMERGENCY RESPONSE', margin, yPosition);
  yPosition += 10;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);

  const responseData = [
    { label: 'Hospital Alerted:', value: incident.hospital_alerted ? 'Yes' : 'No' },
    { label: 'Ambulance Dispatched:', value: incident.ambulance_dispatched ? 'Yes' : 'No' },
    { label: 'Response Time (min):', value: incident.response_time || 'Pending' },
    { label: 'Nearest Hospital:', value: incident.nearest_hospital || 'Unknown' },
    { label: 'Distance (km):', value: incident.hospital_distance?.toFixed(2) || 'N/A' },
    { label: 'ETA (min):', value: incident.eta_minutes || 'N/A' },
  ];

  responseData.forEach((item) => {
    doc.setFont('helvetica', 'bold');
    doc.text(`${item.label}`, margin, yPosition);
    doc.setFont('helvetica', 'normal');
    doc.text(`${item.value}`, margin + 50, yPosition);
    yPosition += 8;
  });

  yPosition += 10;

  // Detections Section
  if (incident.vehicle_count > 0 || incident.violation_types?.length > 0) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    doc.text('DETECTION SUMMARY', margin, yPosition);
    yPosition += 10;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);

    if (incident.vehicle_count > 0) {
      doc.text(`Vehicles Detected: ${incident.vehicle_count}`, margin, yPosition);
      yPosition += 8;
    }

    if (incident.violation_types?.length > 0) {
      doc.text('Violations Detected:', margin, yPosition);
      yPosition += 6;
      incident.violation_types.forEach((violation) => {
        doc.text(`  • ${violation}`, margin + 5, yPosition);
        yPosition += 6;
      });
    }

    yPosition += 8;
  }

  // Footer
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(9);
  doc.setTextColor(128, 128, 128);
  doc.text(
    'This report was automatically generated by RoadRakshak AI Traffic Management System.',
    pageWidth / 2,
    pageHeight - 10,
    { align: 'center' }
  );

  // Save PDF
  const filename = `Incident_${incident.id || new Date().getTime()}_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(filename);

  return filename;
};

export default generateIncidentPDF;
